In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [117]:
diabetes = pd.read_csv('/Users/artemmoskvin/Documents/Data-Science/Data/diabetes_data.csv')
diabetes.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Gender
773,6,103,72,32,190,37.7,0.324,55,0,Female
774,1,71,48,18,76,20.4,0.323,22,0,Female
775,0,117,0,0,0,33.8,0.932,44,0,Female
776,4,154,72,29,126,31.3,0.338,37,0,Female
777,5,147,78,0,0,33.7,0.218,65,0,Female

In [147]:
mask = diabetes.duplicated(subset=None)
diabetes_duplicates = g_diabetes[mask]
print(f'Число найденных дубликатов: {diabetes_duplicates.shape[0]}')
g_diabetes = g_diabetes.drop_duplicates(subset=None)
print(f'Результирующее число записей: {g_diabetes.shape[0]}')

Число найденных дубликатов: 0
Результирующее число записей: 768

/var/folders/bp/7q01yp0929dcj5gt3hpd87tc0000gn/T/ipykernel_1187/4143121271.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  diabetes_duplicates = g_diabetes[mask]

In [159]:
m = g_diabetes.shape[1] #число признаков после удаления столбцов
g_diabetes = g_diabetes.dropna(how='any', thresh=m-2, axis=0)
print(g_diabetes)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6       98             58             33      190  34.0
1              2      112             75             32        0  35.7
2              2      108             64              0        0  30.8
3              8      107             80              0        0  24.6
4              7      136             90              0        0  29.9
..           ...      ...            ...            ...      ...   ...
763            5      139             64             35      140  28.6
764            1       96            122              0        0  22.4
765           10      101             86             37        0  45.6
766            0      141              0              0        0  42.4
767            0      125             96              0        0  22.5

     DiabetesPedigreeFunction  Age  Outcome
0                       0.430   43        0
1                       0.148   21        0
2                       0.158   21        0
3                       0.856   34        0
4                       0.210   50        0
..                        ...  ...      ...
763                     0.411   26        0
764                     0.207   27        0
765                     1.136   38        1
766                     0.205   29        1
767                     0.262   21        0

[768 rows x 9 columns]

In [140]:
#список неинформативных признаков
diabetes_low_information_cols = [] 

#цикл по всем столбцам
for col in diabetes.columns:
    #наибольшая относительная частота в признаке
    top_freq = diabetes[col].value_counts(normalize=True).max()
    #доля уникальных значений от размера признака
    nunique_ratio = diabetes[col].nunique() / diabetes[col].count()
    # сравниваем наибольшую частоту с порогом
    if top_freq > 0.95:
        diabetes_low_information_cols.append(col)
        print(f'{col}: {round(top_freq*100, 2)}% одинаковых значений')
    # сравниваем долю уникальных значений с порогом
    if nunique_ratio > 0.95:
        diabetes_low_information_cols.append(col)
        print(f'{col}: {round(nunique_ratio*100, 2)}% уникальных значений')

Gender: 100.0% одинаковых значений

In [141]:
g_diabetes = diabetes.drop(diabetes_low_information_cols, axis=1)
print(f'Результирующее число признаков: {g_diabetes.shape[1]}')
display(g_diabetes)

Результирующее число признаков: 9

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,98,58,33,190,34.0,0.430,43,0
1,2,112,75,32,0,35.7,0.148,21,0
2,2,108,64,0,0,30.8,0.158,21,0
3,8,107,80,0,0,24.6,0.856,34,0
4,7,136,90,0,0,29.9,0.210,50,0
...,...,...,...,...,...,...,...,...,...
773,6,103,72,32,190,37.7,0.324,55,0
774,1,71,48,18,76,20.4,0.323,22,0
775,0,117,0,0,0,33.8,0.932,44,0
776,4,154,72,29,126,31.3,0.338,37,0
777,5,147,78,0,0,33.7,0.218,65,0

In [142]:
g_diabetes = g_diabetes.dropna(how='any', thresh=2, axis=0)
print(g_diabetes.shape[0])

778

In [143]:
g_diabetes.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
773,6,103,72,32,190,37.7,0.324,55,0
774,1,71,48,18,76,20.4,0.323,22,0
775,0,117,0,0,0,33.8,0.932,44,0
776,4,154,72,29,126,31.3,0.338,37,0
777,5,147,78,0,0,33.7,0.218,65,0

In [59]:
g_diabetes['Insulin'] = g_diabetes['Insulin'].replace(0, float('NaN'))
g_diabetes['Glucose'] = g_diabetes['Glucose'].replace(0, float('NaN'))
g_diabetes['BloodPressure'] = g_diabetes['BloodPressure'].replace(0, float('NaN'))
g_diabetes['SkinThickness'] = g_diabetes['SkinThickness'].replace(0, float('NaN'))
g_diabetes['BMI'] = g_diabetes['BMI'].replace(0, float('NaN'))
g_diabetes.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,5,139.0,64.0,35.0,140.0,28.6,0.411,26,0
764,1,96.0,122.0,NaN,NaN,22.4,0.207,27,0
765,10,101.0,86.0,37.0,NaN,45.6,1.136,38,1
766,0,141.0,NaN,NaN,NaN,42.4,0.205,29,1
767,0,125.0,96.0,NaN,NaN,22.5,0.262,21,0

In [123]:
cols_null_percent = g_diabetes.isnull().mean()
cols_with_null = cols_null_percent[cols_null_percent>0].sort_values(ascending=False)
display(cols_with_null)

Series([], dtype: float64)

In [106]:
thresh = g_diabetes.shape[0]*0.7
#удаляем столбцы, в которых более 30% (100-70) пропусков
g_diabetes = g_diabetes.dropna(how='any', thresh=thresh, axis=1)
#удаляем записи, в которых есть хотя бы 1 пропуск
g_diabetes = g_diabetes.dropna(how='any', axis=0)
#отображаем результирующую долю пропусков
g_diabetes.isnull().mean()
print(g_diabetes.shape)

(532, 8)

In [100]:
values = {
    'Pregnancies': g_diabetes_prop['Pregnancies'].median(),
    'Glucose': g_diabetes_prop['Glucose'].median(),
    'BloodPressure': g_diabetes_prop['BloodPressure'].median(),
    'SkinThickness': g_diabetes_prop['SkinThickness'].median(),
    'Insulin': g_diabetes_prop['Insulin'].median(),
    'BMI': g_diabetes_prop['BMI'].median(),
    'DiabetesPedigreeFunction': g_diabetes_prop['DiabetesPedigreeFunction'].median(),
    'Age': g_diabetes_prop['Age'].median(),
    'Outcome': g_diabetes_prop['Outcome'].median()
}
g_diabetes_prop = g_diabetes_prop.fillna(values)
g_diabetes_prop['SkinThickness'].median()

29.0

In [90]:
g_diabetes_prop.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,5,139.0,64.0,35.0,140.0,28.6,0.411,26,0
764,1,96.0,122.0,29.0,125.0,22.4,0.207,27,0
765,10,101.0,86.0,37.0,125.0,45.6,1.136,38,1
766,0,141.0,72.0,29.0,125.0,42.4,0.205,29,1
767,0,125.0,96.0,29.0,125.0,22.5,0.262,21,0

In [85]:
g_diabetes_prop_sum = g_diabetes_prop['SkinThickness'].sum()
g_diabetes_prop_count = g_diabetes_prop['SkinThickness'].count()
g_diabetes_prop_mean = g_diabetes_prop_sum / g_diabetes_prop_count
print(g_diabetes_prop_mean)

29.108072916666668

In [92]:
def outliers_iqr(data, feature):
    x = data[feature]
    quartile_1, quartile_3 = x.quantile(0.25), x.quantile(0.75),
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    outliers = data[(x<lower_bound) | (x > upper_bound)]
    cleaned = data[(x>lower_bound) & (x < upper_bound)]
    return outliers, cleaned
outliers, cleaned = outliers_iqr(g_diabetes_prop, 'DiabetesPedigreeFunction')
print(f'Число выбросов по методу Тьюки: {outliers.shape[0]}')
print(f'Результирующее число записей: {cleaned.shape[0]}')

Число выбросов по методу Тьюки: 29
Результирующее число записей: 739

In [93]:
def outliers_iqr_mod(data, feature, log_scale=True, left=3, right=3):
    if log_scale:
        x = np.log(data[feature])
    else:
        x = data[feature]
    quartile_1, quartile_3 = x.quantile(0.25), x.quantile(0.75),
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * left)
    upper_bound = quartile_3 + (iqr * right)
    outliers = data[(x<lower_bound) | (x> upper_bound)]
    cleaned = data[(x>lower_bound) & (x < upper_bound)]
    return outliers, cleaned
outliers, cleaned = outliers_iqr_mod(g_diabetes_prop, 'DiabetesPedigreeFunction')
print({outliers.shape[0]})
print({cleaned.shape[0]})

{0}
{768}

In [91]:
def outliers_z_score(data, feature, log_scale=False):
    if log_scale:
        x = np.log(data[feature]+1)
    else:
        x = data[feature]
    mu = x.mean()
    sigma = x.std()
    lower_bound = mu - 3 * sigma
    upper_bound = mu + 3 * sigma
    outliers = data[(x < lower_bound) | (x > upper_bound)]
    cleaned = data[(x > lower_bound) & (x < upper_bound)]
    return outliers, cleaned
outliers, cleaned = outliers_z_score(g_diabetes_prop, 'SkinThickness', log_scale=False)
print(f'Число выбросов по методу z-отклонения: {outliers.shape[0]}')
print(f'Результирующее число записей: {cleaned.shape[0]}')

Число выбросов по методу z-отклонения: 4
Результирующее число записей: 764